var searchData=
[
  ['customcontrols',['CustomControls',['../da/d69/namespace_polygons_1_1_forms_1_1_custom_controls.html',1,'Polygons::Forms']]],
  ['dialogforms',['DialogForms',['../d0/d52/namespace_polygons_1_1_forms_1_1_dialog_forms.html',1,'Polygons::Forms']]],
  ['fitnesscalculators',['FitnessCalculators',['../db/dd8/namespace_polygons_1_1_g_a_1_1_fitness_calculators.html',1,'Polygons::GA']]],
  ['forms',['Forms',['../d9/dad/namespace_polygons_1_1_forms.html',1,'Polygons']]],
  ['ga',['GA',['../dd/d98/namespace_polygons_1_1_g_a.html',1,'Polygons']]],
  ['polygenetic_20algorithm',['PolyGenetic Algorithm',['../db/d15/md__c_1___code_projects__poly_ga__r_e_a_d_m_e.html',1,'']]],
  ['polygalauncher',['PolyGaLauncher',['../d1/dc9/namespace_poly_ga_launcher.html',1,'']]],
  ['polygon',['Polygon',['../da/d09/class_polygons_1_1_polygon.html',1,'Polygon'],['../db/dd3/class_polygons_1_1_g_a_1_1_polygon_individual.html#af8e2e51fa22d867206ea26bd79a29423',1,'Polygons.GA.PolygonIndividual.Polygon()'],['../da/d09/class_polygons_1_1_polygon.html#ab17f7af86d9c6a41ca66105c713630f7',1,'Polygons.Polygon.Polygon(List&lt; Point &gt; vertices, Color outlineColor=default(Color), string name=default(string))'],['../da/d09/class_polygons_1_1_polygon.html#aa27e4af9f408b1310be4091ec45b5d86',1,'Polygons.Polygon.Polygon(Polygon original, double resizeFactor)']]],
  ['polygon_2ecs',['Polygon.cs',['../d9/d4b/_polygon_8cs.html',1,'']]],
  ['polygonadapter',['PolygonAdapter',['../d2/dbb/class_polygons_1_1_g_a_1_1_polygon_adapter.html',1,'PolygonAdapter'],['../d2/dbb/class_polygons_1_1_g_a_1_1_polygon_adapter.html#a75b578528fc3adbc950c425d58fb9099',1,'Polygons.GA.PolygonAdapter.PolygonAdapter()']]],
  ['polygonadapter_2ecs',['PolygonAdapter.cs',['../d7/dd6/_polygon_adapter_8cs.html',1,'']]],
  ['polygoncreationform',['PolygonCreationForm',['../db/d82/class_polygons_1_1_forms_1_1_polygon_creation_form.html',1,'PolygonCreationForm'],['../db/d82/class_polygons_1_1_forms_1_1_polygon_creation_form.html#a585595ac06d34eeb3f0e673d274d286b',1,'Polygons.Forms.PolygonCreationForm.PolygonCreationForm()']]],
  ['polygoncreationform_2ecs',['PolygonCreationForm.cs',['../d4/dc1/_polygon_creation_form_8cs.html',1,'']]],
  ['polygoncreationform_2edesigner_2ecs',['PolygonCreationForm.Designer.cs',['../d8/d2b/_polygon_creation_form_8_designer_8cs.html',1,'']]],
  ['polygongasettings_2edesigner_2ecs',['PolygonGaSettings.Designer.cs',['../d7/d28/_polygon_ga_settings_8_designer_8cs.html',1,'']]],
  ['polygongenerator',['PolygonGenerator',['../d0/d8c/class_polygons_1_1_polygon_generator.html',1,'Polygons']]],
  ['polygongenerator_2ecs',['PolygonGenerator.cs',['../dc/d3e/_polygon_generator_8cs.html',1,'']]],
  ['polygonindividual',['PolygonIndividual',['../db/dd3/class_polygons_1_1_g_a_1_1_polygon_individual.html',1,'PolygonIndividual'],['../db/dd3/class_polygons_1_1_g_a_1_1_polygon_individual.html#ad3b4590d8fea313de429aa9244bd7c69',1,'Polygons.GA.PolygonIndividual.PolygonIndividual()'],['../db/dd3/class_polygons_1_1_g_a_1_1_polygon_individual.html#ae5a04db4fdb5dfc6b02919703929a8b7',1,'Polygons.GA.PolygonIndividual.PolygonIndividual(Polygon p)'],['../db/dd3/class_polygons_1_1_g_a_1_1_polygon_individual.html#a9e6589442bdc4f1fdefc388d71237ac2',1,'Polygons.GA.PolygonIndividual.PolygonIndividual(IEnumerable&lt; IPolygonGene &gt; genome, string name, Color color)']]],
  ['polygonindividual_2ecs',['PolygonIndividual.cs',['../df/d9b/_polygon_individual_8cs.html',1,'']]],
  ['polygonnormalizedtobox',['PolygonNormalizedToBox',['../db/d5d/class_polygons_1_1_polygon_visualizer.html#a56d23e88e87da306dfba7fc99d1b086c',1,'Polygons.PolygonVisualizer.PolygonNormalizedToBox(this Polygon p, PictureBox normalizeTo)'],['../db/d5d/class_polygons_1_1_polygon_visualizer.html#a16e41a29d8cf912913b9d1839eca14f4',1,'Polygons.PolygonVisualizer.PolygonNormalizedToBox(this Polygon p, int width, int height)']]],
  ['polygonpaths_2ecs',['PolygonPaths.cs',['../d9/de4/_polygon_paths_8cs.html',1,'']]],
  ['polygons',['Polygons',['../de/db8/namespace_polygons.html',1,'']]],
  ['polygonvisualizer',['PolygonVisualizer',['../db/d5d/class_polygons_1_1_polygon_visualizer.html',1,'Polygons']]],
  ['polygonvisualizer_2ecs',['PolygonVisualizer.cs',['../da/d1f/_polygon_visualizer_8cs.html',1,'']]],
  ['polygonxmlhandler',['PolygonXmlHandler',['../d9/d87/class_polygons_1_1_polygon_xml_handler.html',1,'Polygons']]],
  ['polygonxmlhandler_2ecs',['PolygonXmlHandler.cs',['../d5/dd7/_polygon_xml_handler_8cs.html',1,'']]],
  ['population',['Population',['../dd/d05/class_genetic___algorithm_1_1_g_a_1_1_generics_1_1_population.html',1,'Population&lt; TIndividual, TGene &gt;'],['../dd/d05/class_genetic___algorithm_1_1_g_a_1_1_generics_1_1_population.html#a73aba8fd4ea796ce4c10744dcd1570bf',1,'Genetic_Algorithm.GA.Generics.Population.Population(int randomIndividuals=0, int desiredSize=0)'],['../dd/d05/class_genetic___algorithm_1_1_g_a_1_1_generics_1_1_population.html#a3fa2659076c59b10884970d9d9b76cdb',1,'Genetic_Algorithm.GA.Generics.Population.Population(Population&lt; TIndividual, TGene &gt; template)']]],
  ['population_2ecs',['Population.cs',['../de/dc0/_population_8cs.html',1,'']]],
  ['populationgeneratorform',['PopulationGeneratorForm',['../d5/d21/class_polygons_1_1_forms_1_1_population_generator_form.html',1,'PopulationGeneratorForm'],['../d5/d21/class_polygons_1_1_forms_1_1_population_generator_form.html#a4e771ad717629646a591c49d2861e123',1,'Polygons.Forms.PopulationGeneratorForm.PopulationGeneratorForm()']]],
  ['populationgeneratorform_2ecs',['PopulationGeneratorForm.cs',['../d1/d1f/_population_generator_form_8cs.html',1,'']]],
  ['populationgeneratorform_2edesigner_2ecs',['PopulationGeneratorForm.Designer.cs',['../dd/d13/_population_generator_form_8_designer_8cs.html',1,'']]],
  ['populationsize',['PopulationSize',['../da/d51/class_genetic___algorithm_1_1_utils_1_1_settings_accessor.html#ad4d499d40c23f69e9186b44df18ed6cb',1,'Genetic_Algorithm::Utils::SettingsAccessor']]],
  ['processdialogkey',['ProcessDialogKey',['../d0/dc1/class_polygons_1_1_forms_1_1_ga_viewer_form.html#ad39dc194815a131d6e155978b8684f3a',1,'Polygons.Forms.GaViewerForm.ProcessDialogKey()'],['../db/d82/class_polygons_1_1_forms_1_1_polygon_creation_form.html#ad39dc194815a131d6e155978b8684f3a',1,'Polygons.Forms.PolygonCreationForm.ProcessDialogKey()'],['../d5/d21/class_polygons_1_1_forms_1_1_population_generator_form.html#ad39dc194815a131d6e155978b8684f3a',1,'Polygons.Forms.PopulationGeneratorForm.ProcessDialogKey()']]],
  ['program',['Program',['../d6/dee/class_poly_ga_launcher_1_1_program.html',1,'PolyGaLauncher']]],
  ['program_2ecs',['Program.cs',['../dd/d5c/_program_8cs.html',1,'']]],
  ['properties',['Properties',['../d2/dee/namespace_poly_ga_launcher_1_1_properties.html',1,'PolyGaLauncher.Properties'],['../d1/d2e/namespace_polygons_1_1_properties.html',1,'Polygons.Properties']]],
  ['utils',['Utils',['../de/dc9/namespace_polygons_1_1_utils.html',1,'Polygons']]]
];
