var searchData=
[
  ['customcontrols',['CustomControls',['../da/d69/namespace_polygons_1_1_forms_1_1_custom_controls.html',1,'Polygons::Forms']]],
  ['dialogforms',['DialogForms',['../d0/d52/namespace_polygons_1_1_forms_1_1_dialog_forms.html',1,'Polygons::Forms']]],
  ['fitnesscalculators',['FitnessCalculators',['../db/dd8/namespace_polygons_1_1_g_a_1_1_fitness_calculators.html',1,'Polygons::GA']]],
  ['forms',['Forms',['../d9/dad/namespace_polygons_1_1_forms.html',1,'Polygons']]],
  ['ga',['GA',['../dd/d98/namespace_polygons_1_1_g_a.html',1,'Polygons']]],
  ['helperforms',['HelperForms',['../d5/dbd/namespace_polygons_1_1_forms_1_1_helper_forms.html',1,'Polygons::Forms']]],
  ['polygenetic_20algorithm',['PolyGenetic Algorithm',['../dd/dbf/md__c_1___code_projects__genetic__algorithm_-__polygons__r_e_a_d_m_e.html',1,'']]],
  ['paths',['Paths',['../de/dfe/class_polygons_1_1_paths.html',1,'Polygons']]],
  ['paths_2ecs',['Paths.cs',['../df/d19/_paths_8cs.html',1,'']]],
  ['polygalauncher',['PolyGaLauncher',['../d1/dc9/namespace_poly_ga_launcher.html',1,'']]],
  ['polygon',['Polygon',['../da/d09/class_polygons_1_1_polygon.html',1,'Polygons.Polygon'],['../db/dd3/class_polygons_1_1_g_a_1_1_polygon_individual.html#ac74d97cbbc90e83d50da09b021da2c2a',1,'Polygons.GA.PolygonIndividual.Polygon()'],['../da/d09/class_polygons_1_1_polygon.html#a49a7c47825355af3f9fbce2e25847034',1,'Polygons.Polygon.Polygon(List&lt; Point &gt; vertices, Color outlineColor=default(Color), string name=default(string))'],['../da/d09/class_polygons_1_1_polygon.html#abbf651489f1178088fbf6a86116e2e19',1,'Polygons.Polygon.Polygon(Polygon original, double resizeFactor)']]],
  ['polygon_2ecs',['Polygon.cs',['../d9/d4b/_polygon_8cs.html',1,'']]],
  ['polygonadapter',['PolygonAdapter',['../d2/dbb/class_polygons_1_1_g_a_1_1_polygon_adapter.html',1,'Polygons.GA.PolygonAdapter'],['../d2/dbb/class_polygons_1_1_g_a_1_1_polygon_adapter.html#a6ed418656af3f16d781306c34a87a3d0',1,'Polygons.GA.PolygonAdapter.PolygonAdapter()']]],
  ['polygonadapter_2ecs',['PolygonAdapter.cs',['../d7/dd6/_polygon_adapter_8cs.html',1,'']]],
  ['polygoncreationform',['PolygonCreationForm',['../db/d82/class_polygons_1_1_forms_1_1_polygon_creation_form.html',1,'Polygons.Forms.PolygonCreationForm'],['../db/d82/class_polygons_1_1_forms_1_1_polygon_creation_form.html#a5be781ff8cbf728bd62188142af10f5c',1,'Polygons.Forms.PolygonCreationForm.PolygonCreationForm()']]],
  ['polygoncreationform_2ecs',['PolygonCreationForm.cs',['../d4/dc1/_polygon_creation_form_8cs.html',1,'']]],
  ['polygoncreationform_2edesigner_2ecs',['PolygonCreationForm.Designer.cs',['../d8/d2b/_polygon_creation_form_8_designer_8cs.html',1,'']]],
  ['polygongasettings_2edesigner_2ecs',['PolygonGaSettings.Designer.cs',['../d7/d28/_polygon_ga_settings_8_designer_8cs.html',1,'']]],
  ['polygonindividual',['PolygonIndividual',['../db/dd3/class_polygons_1_1_g_a_1_1_polygon_individual.html',1,'Polygons.GA.PolygonIndividual'],['../db/dd3/class_polygons_1_1_g_a_1_1_polygon_individual.html#a4ec2e558d5655ad0e68dc9728d491041',1,'Polygons.GA.PolygonIndividual.PolygonIndividual()'],['../db/dd3/class_polygons_1_1_g_a_1_1_polygon_individual.html#afcc358d6a6521377f644a50772b959e7',1,'Polygons.GA.PolygonIndividual.PolygonIndividual(Polygon p)'],['../db/dd3/class_polygons_1_1_g_a_1_1_polygon_individual.html#a4ee92bf9c5d473bbb77bf0f65453467f',1,'Polygons.GA.PolygonIndividual.PolygonIndividual(IEnumerable&lt; IPolygonGene &gt; genome, string name, Color color)']]],
  ['polygonindividual_2ecs',['PolygonIndividual.cs',['../df/d9b/_polygon_individual_8cs.html',1,'']]],
  ['polygonnormalizedtobox',['PolygonNormalizedToBox',['../db/d5d/class_polygons_1_1_polygon_visualizer.html#aeb8acc68ff648a567ccc6f47eaf624fd',1,'Polygons.PolygonVisualizer.PolygonNormalizedToBox(Polygon p, PictureBox normalizeTo)'],['../db/d5d/class_polygons_1_1_polygon_visualizer.html#a7858568bd571eb7535ea5a840aa5c808',1,'Polygons.PolygonVisualizer.PolygonNormalizedToBox(Polygon p, int width, int height)']]],
  ['polygons',['Polygons',['../dc/d01/class_polygons_1_1_polygons.html',1,'Polygons.Polygons'],['../de/db8/namespace_polygons.html',1,'Polygons']]],
  ['polygons_2ecs',['Polygons.cs',['../db/d54/_polygons_8cs.html',1,'']]],
  ['polygonsavedshapesfolder',['PolygonSavedShapesFolder',['../de/dfe/class_polygons_1_1_paths.html#a16e6e798155e7ed285b884b9cdd8da2e',1,'Polygons::Paths']]],
  ['polygonsavedshapesfoldernobacklash',['PolygonSavedShapesFolderNoBacklash',['../de/dfe/class_polygons_1_1_paths.html#a18d1981262058eeb9195ec603ee317ce',1,'Polygons::Paths']]],
  ['polygonvisualizer',['PolygonVisualizer',['../db/d5d/class_polygons_1_1_polygon_visualizer.html',1,'Polygons']]],
  ['polygonvisualizer_2ecs',['PolygonVisualizer.cs',['../da/d1f/_polygon_visualizer_8cs.html',1,'']]],
  ['polygonxmlhandler',['PolygonXmlHandler',['../d9/d87/class_polygons_1_1_polygon_xml_handler.html',1,'Polygons']]],
  ['polygonxmlhandler_2ecs',['PolygonXmlHandler.cs',['../d5/dd7/_polygon_xml_handler_8cs.html',1,'']]],
  ['population',['Population',['../dd/d05/class_genetic___algorithm_1_1_g_a_1_1_generics_1_1_population.html',1,'Genetic_Algorithm.GA.Generics.Population&lt; TIndividual, TGene &gt;'],['../dd/d05/class_genetic___algorithm_1_1_g_a_1_1_generics_1_1_population.html#a5ba5440cb3c02cc21fa0d96845409d6c',1,'Genetic_Algorithm.GA.Generics.Population.Population(int randomIndividuals=0, int desiredSize=0)'],['../dd/d05/class_genetic___algorithm_1_1_g_a_1_1_generics_1_1_population.html#a7ca9432c78efa246d1f0b0289df6b2c0',1,'Genetic_Algorithm.GA.Generics.Population.Population(Population&lt; TIndividual, TGene &gt; template)']]],
  ['population_2ecs',['Population.cs',['../de/dc0/_population_8cs.html',1,'']]],
  ['populationgeneratorform',['PopulationGeneratorForm',['../d5/d21/class_polygons_1_1_forms_1_1_population_generator_form.html',1,'Polygons.Forms.PopulationGeneratorForm'],['../d5/d21/class_polygons_1_1_forms_1_1_population_generator_form.html#a83eccd0c2d144e65a0a62ad20699b9bb',1,'Polygons.Forms.PopulationGeneratorForm.PopulationGeneratorForm()']]],
  ['populationgeneratorform_2ecs',['PopulationGeneratorForm.cs',['../d1/d1f/_population_generator_form_8cs.html',1,'']]],
  ['populationgeneratorform_2edesigner_2ecs',['PopulationGeneratorForm.Designer.cs',['../dd/d13/_population_generator_form_8_designer_8cs.html',1,'']]],
  ['populationsize',['PopulationSize',['../da/d51/class_genetic___algorithm_1_1_utils_1_1_settings_accessor.html#ad6ab078464d84cf8210c5112ffecde6a',1,'Genetic_Algorithm::Utils::SettingsAccessor']]],
  ['processdialogkey',['ProcessDialogKey',['../d0/dc1/class_polygons_1_1_forms_1_1_ga_viewer_form.html#aa2f5dfef4251555a7db2284a6eaee371',1,'Polygons.Forms.GaViewerForm.ProcessDialogKey()'],['../db/d82/class_polygons_1_1_forms_1_1_polygon_creation_form.html#a8cdfc3ca48d228c81d8c6d36995c517a',1,'Polygons.Forms.PolygonCreationForm.ProcessDialogKey()'],['../d5/d21/class_polygons_1_1_forms_1_1_population_generator_form.html#aef693a7143f630f495883c3339e920ab',1,'Polygons.Forms.PopulationGeneratorForm.ProcessDialogKey()']]],
  ['program',['Program',['../d6/dee/class_poly_ga_launcher_1_1_program.html',1,'PolyGaLauncher']]],
  ['program_2ecs',['Program.cs',['../dd/d5c/_program_8cs.html',1,'']]],
  ['properties',['Properties',['../d2/dee/namespace_poly_ga_launcher_1_1_properties.html',1,'PolyGaLauncher.Properties'],['../d1/d2e/namespace_polygons_1_1_properties.html',1,'Polygons.Properties']]],
  ['utils',['Utils',['../de/dc9/namespace_polygons_1_1_utils.html',1,'Polygons']]]
];
