.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/GA/FitnessCalculators/BasicSymmetryCalculator.cs" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/GA/FitnessCalculators/BasicSymmetryCalculator.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPolygons\&.GA\&.FitnessCalculators\&.BasicSymmetryFitnessCalculator\fP"
.br
.RI "For every \fBIPolygonGene\fP, finds its closest Y axis mirrored relative and decreases fitness based on the distance difference from an ideal relative's position "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPolygons\&.GA\&.FitnessCalculators\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
