.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Genetic Algorithm/Genetic Algorithm/Utils Directory Reference" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Genetic Algorithm/Genetic Algorithm/Utils Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSettingsAccessor\&.cs\fP"
.br
.ti -1c
.RI "file \fBUniqueRandom\&.cs\fP"
.br
.in -1c
