.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Genetic Algorithm/Genetic Algorithm/GA/Generics Directory Reference" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Genetic Algorithm/Genetic Algorithm/GA/Generics Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDelegatesAndEvents\&.cs\fP"
.br
.ti -1c
.RI "file \fBGeneticAlgorithm\&.cs\fP"
.br
.ti -1c
.RI "file \fBGeneticAlgorithmAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBIFitnessCalculator\&.cs\fP"
.br
.ti -1c
.RI "file \fBIGene\&.cs\fP"
.br
.ti -1c
.RI "file \fBIGeneticAlgorithmAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBIIndividual\&.cs\fP"
.br
.ti -1c
.RI "file \fBPopulation\&.cs\fP"
.br
.in -1c
