.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/obj Directory Reference" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/obj Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDebug\fP"
.br
.ti -1c
.RI "directory \fBRelease\fP"
.br
.ti -1c
.RI "directory \fBx86\fP"
.br
.in -1c
