.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/GA Directory Reference" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/GA Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBFitnessCalculators\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIPolygonGene\&.cs\fP"
.br
.ti -1c
.RI "file \fBPolygonAdapter\&.cs\fP"
.br
.ti -1c
.RI "file \fBPolygonIndividual\&.cs\fP"
.br
.ti -1c
.RI "file \fBSimplePolygonGene\&.cs\fP"
.br
.in -1c
