.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/GA/FitnessCalculators Directory Reference" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/GA/FitnessCalculators Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBasicSymmetryCalculator\&.cs\fP"
.br
.ti -1c
.RI "file \fBCalculatorRetriever\&.cs\fP"
.br
.ti -1c
.RI "file \fBSymmetryIntersectionPenaltyCalculator\&.cs\fP"
.br
.in -1c
