.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/Forms/CustomControls Directory Reference" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/Forms/CustomControls Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGaComponentIcon\&.cs\fP"
.br
.ti -1c
.RI "file \fBGaComponentIcon\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBLabeledPolygonImage\&.cs\fP"
.br
.ti -1c
.RI "file \fBLabeledPolygonImage\&.Designer\&.cs\fP"
.br
.in -1c
