.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/PolyGaLauncher/Properties Directory Reference" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/PolyGaLauncher/Properties Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAssemblyInfo\&.cs\fP"
.br
.ti -1c
.RI "file \fBResources\&.Designer\&.cs\fP"
.br
.ti -1c
.RI "file \fBSettings\&.Designer\&.cs\fP"
.br
.in -1c
