.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/GA/FitnessCalculators/CalculatorRetriever.cs" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/GA/FitnessCalculators/CalculatorRetriever.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPolygons\&.GA\&.FitnessCalculators\&.CalculatorRetriever\fP"
.br
.RI "Provides a centralised access to fitness calculators intended for \fBPolygonIndividual\fPs "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPolygons\&.GA\&.FitnessCalculators\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
