.TH "Genetic_Algorithm.GA.Generics.NumberedPopulation< TIndividual, TGene >" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm.GA.Generics.NumberedPopulation< TIndividual, TGene > \- Extended population with additional information about its number as a generation in \fBGA\fP and the highest fitness value achieved  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGenetic_Algorithm\&.GA\&.Generics\&.Population< TIndividual, TGene >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNumberedPopulation\fP (\fBPopulation\fP< TIndividual, TGene > population, int number)"
.br
.RI "Create a population with additional \fBGA\fP information "
.ti -1c
.RI "void \fBTrySetFitness\fP (double value)"
.br
.RI "Only allows to set \fBTopFitness\fP if it hasn't been initialised yet (in case top fitness couldn't be acquired during construction) "
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.RI "String representation of \fBNumberedPopulation<TIndividual, TGene>\fP "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBNumber\fP\fC [get]\fP"
.br
.RI "Ordinal number of the generation stored in the population "
.ti -1c
.RI "double \fBTopFitness\fP\fC [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Extended population with additional information about its number as a generation in \fBGA\fP and the highest fitness value achieved 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fITIndividual\fP Type of IIndividual<IGene> in the population
.br
\fITGene\fP Type of \fBIGene\fP in the population
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fITIndividual\fP : \fI\fBIIndividual\fP<TGene>\fP
.TP
\fITIndividual\fP : \fInew()\fP
.TP
\fITGene\fP : \fI\fBIGene\fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBGenetic_Algorithm\&.GA\&.Generics\&.NumberedPopulation\fP< TIndividual, TGene >\&.\fBNumberedPopulation\fP (\fBPopulation\fP< TIndividual, TGene > population, int number)"

.PP
Create a population with additional \fBGA\fP information 
.PP
\fBParameters:\fP
.RS 4
\fIpopulation\fP Individuals to store
.br
\fInumber\fP N-th generation in a \fBGA\fP
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override string \fBGenetic_Algorithm\&.GA\&.Generics\&.NumberedPopulation\fP< TIndividual, TGene >\&.ToString ()"

.PP
String representation of \fBNumberedPopulation<TIndividual, TGene>\fP 
.PP
\fBReturns:\fP
.RS 4

.RE
.PP

.SS "void \fBGenetic_Algorithm\&.GA\&.Generics\&.NumberedPopulation\fP< TIndividual, TGene >\&.TrySetFitness (double value)"

.PP
Only allows to set \fBTopFitness\fP if it hasn't been initialised yet (in case top fitness couldn't be acquired during construction) 
.PP
\fBParameters:\fP
.RS 4
\fIvalue\fP 
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "int \fBGenetic_Algorithm\&.GA\&.Generics\&.NumberedPopulation\fP< TIndividual, TGene >\&.Number\fC [get]\fP"

.PP
Ordinal number of the generation stored in the population 
.SS "double \fBGenetic_Algorithm\&.GA\&.Generics\&.NumberedPopulation\fP< TIndividual, TGene >\&.TopFitness\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
