.TH "Genetic_Algorithm.GA.Generics.IGene" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm.GA.Generics.IGene \- Stores an encoded representation of any trait which can be mutated  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGenetic_Algorithm\&.GA\&.Generics\&.IGene< out out TEncoded >\fP\&.
.SH "Detailed Description"
.PP 
Stores an encoded representation of any trait which can be mutated 



.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
