.TH "Genetic_Algorithm.GA.Generics" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm.GA.Generics
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGaEventArgs\fP"
.br
.RI "Store relevant information for genetic algoritms to be passed for Ga event handlers "
.ti -1c
.RI "class \fBGeneticAlgorithm\fP"
.br
.RI "Main driver class to handle logic of the genetic algorithm "
.ti -1c
.RI "class \fBGeneticAlgorithmAdapter\fP"
.br
.RI "Provides methods for manipulating populations in \fBGA\fP to produce new generations "
.ti -1c
.RI "interface \fBIFitnessCalculator\fP"
.br
.RI "Evaluates IIndividual<IGene>s and sets + returns their calculated fitness score "
.ti -1c
.RI "interface \fBIGene\fP"
.br
.RI "Stores an encoded representation of any trait which can be mutated "
.ti -1c
.RI "interface \fBIGeneticAlgorithmAdapter\fP"
.br
.RI "Provides methods for manipulating populations in \fBGA\fP to produce new generations "
.ti -1c
.RI "interface \fBIIndividual\fP"
.br
.RI "Represents an organism/individual in a genetic algorithm "
.ti -1c
.RI "class \fBNumberedPopulation\fP"
.br
.RI "Extended population with additional information about its number as a generation in \fBGA\fP and the highest fitness value achieved "
.ti -1c
.RI "class \fBPopulation\fP"
.br
.RI "Collection of individuals in a genetic algorithm "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "delegate void \fBGenerationCompleteEventHandler< TIndividual, TGene >\fP (\fBGaEventArgs\fP< TIndividual, TGene > ge)"
.br
.ti -1c
.RI "delegate void \fBGaInitialisedEventHandler< TIndividual, TGene >\fP (\fBGaEventArgs\fP< TIndividual, TGene > ge)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "delegate void Genetic_Algorithm\&.GA\&.Generics\&.GaInitialisedEventHandler< TIndividual, TGene > (\fBGaEventArgs\fP< TIndividual, TGene > ge)"

.PP
\fBType Constraints\fP
.TP
\fITIndividual\fP : \fIIIndividual<TGene>\fP
.TP
\fITIndividual\fP : \fInew()\fP
.TP
\fITGene\fP : \fIIGene\fP
.SS "delegate void Genetic_Algorithm\&.GA\&.Generics\&.GenerationCompleteEventHandler< TIndividual, TGene > (\fBGaEventArgs\fP< TIndividual, TGene > ge)"

.PP
\fBType Constraints\fP
.TP
\fITIndividual\fP : \fIIIndividual<TGene>\fP
.TP
\fITIndividual\fP : \fInew()\fP
.TP
\fITGene\fP : \fIIGene\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
