.TH "Genetic_Algorithm.GA.Generics.GaEventArgs< TIndividual, TGene >" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm.GA.Generics.GaEventArgs< TIndividual, TGene > \- Store relevant information for genetic algoritms to be passed for Ga event handlers  

.SH SYNOPSIS
.br
.PP
.PP
Inherits EventArgs\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGaEventArgs\fP (\fBPopulation\fP< TIndividual, TGene > eventPopulation, int populationNumber)"
.br
.RI "Create a \fBGaEventArgs<TIndividual, TGene>\fP instance "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBNumberedPopulation\fP< TIndividual, TGene > \fBSavedPopulation\fP\fC [get]\fP"
.br
.RI "A collection of individuals with additional information about their generation's number within the running \fBGA\fP and the best individual within the population "
.in -1c
.SH "Detailed Description"
.PP 
Store relevant information for genetic algoritms to be passed for Ga event handlers 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fITIndividual\fP Type of the used IIndividual<IGene> in the event population
.br
\fITGene\fP Type of the \fBIGene\fP in the event population
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fITIndividual\fP : \fI\fBIIndividual\fP<TGene>\fP
.TP
\fITIndividual\fP : \fInew()\fP
.TP
\fITGene\fP : \fI\fBIGene\fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBGenetic_Algorithm\&.GA\&.Generics\&.GaEventArgs\fP< TIndividual, TGene >\&.\fBGaEventArgs\fP (\fBPopulation\fP< TIndividual, TGene > eventPopulation, int populationNumber)"

.PP
Create a \fBGaEventArgs<TIndividual, TGene>\fP instance 
.PP
\fBParameters:\fP
.RS 4
\fIeventPopulation\fP Current generation for the event
.br
\fIpopulationNumber\fP Current number of the generation
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBNumberedPopulation\fP<TIndividual, TGene> \fBGenetic_Algorithm\&.GA\&.Generics\&.GaEventArgs\fP< TIndividual, TGene >\&.SavedPopulation\fC [get]\fP"

.PP
A collection of individuals with additional information about their generation's number within the running \fBGA\fP and the best individual within the population 

.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
