.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Genetic Algorithm/Genetic Algorithm/GA/Generics/GeneticAlgorithmAdapter.cs" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Genetic Algorithm/Genetic Algorithm/GA/Generics/GeneticAlgorithmAdapter.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenetic_Algorithm\&.GA\&.Generics\&.GeneticAlgorithmAdapter< TIndividual, TGene >\fP"
.br
.RI "Provides methods for manipulating populations in \fBGA\fP to produce new generations "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGenetic_Algorithm\&.GA\&.Generics\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
