.TH "Genetic_Algorithm.GA.Generics.IFitnessCalculator< TIndividual, TGene >" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm.GA.Generics.IFitnessCalculator< TIndividual, TGene > \- Evaluates IIndividual<IGene>s and sets + returns their calculated fitness score  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IComparer< TIndividual >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "double \fBIndividualFitness\fP (TIndividual individual)"
.br
.RI "Calculate fitness value for the whole individual "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.RI "Name of the calculator to be used in calculators selection (improved readability) "
.in -1c
.SH "Detailed Description"
.PP 
Evaluates IIndividual<IGene>s and sets + returns their calculated fitness score 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fITIndividual\fP 
.br
\fITGene\fP 
.RE
.PP

.PP
\fBType Constraints\fP
.TP
\fITIndividual\fP : \fI\fBIIndividual\fP<TGene>\fP
.TP
\fITGene\fP : \fI\fBIGene\fP\fP
.SH "Member Function Documentation"
.PP 
.SS "double \fBGenetic_Algorithm\&.GA\&.Generics\&.IFitnessCalculator\fP< TIndividual, TGene >\&.IndividualFitness (TIndividual individual)"

.PP
Calculate fitness value for the whole individual 
.PP
\fBParameters:\fP
.RS 4
\fIindividual\fP \fBGA\fP Individual to calculate for
.RE
.PP
\fBReturns:\fP
.RS 4
Fitness score
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "string \fBGenetic_Algorithm\&.GA\&.Generics\&.IFitnessCalculator\fP< TIndividual, TGene >\&.Name\fC [get]\fP"

.PP
Name of the calculator to be used in calculators selection (improved readability) 

.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
