.TH "Genetic_Algorithm.Utils.SettingsAccessor" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm.Utils.SettingsAccessor \- Serves as an intermediary to the Genetic Algorithm's GaSettings\&.Default  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBSaveSettings\fP ()"
.br
.RI "Write current settings state to permanent settings file "
.ti -1c
.RI "static void \fBResetToDefaults\fP ()"
.br
.RI "Retrieve \fBGA\fP parameters from a backup settings file "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static bool \fBElitism\fP\fC [get, set]\fP"
.br
.RI "Indicates whether top individual of population should always be guaranteed to continue without changes "
.ti -1c
.RI "static double \fBCrossoverProbability\fP\fC [get, set]\fP"
.br
.RI "Chance that two individuals will generate a meiotic offspring instead of continuing unchanged "
.ti -1c
.RI "static double \fBSteadyStateSurvivalRate\fP\fC [get, set]\fP"
.br
.RI "Percentage of individuals to automatically survive each generation "
.ti -1c
.RI "static double \fBMutationProbability\fP\fC [get, set]\fP"
.br
.RI "Chance that a single gene will mutate "
.ti -1c
.RI "static int \fBPopulationSize\fP\fC [get, set]\fP"
.br
.RI "Number of individuals per generation "
.ti -1c
.RI "static \fBSelectionType\fP \fBSelection\fP\fC [get, set]\fP"
.br
.RI "\fBSelectionType\fP currently used "
.in -1c
.SH "Detailed Description"
.PP 
Serves as an intermediary to the Genetic Algorithm's GaSettings\&.Default 


.SH "Member Function Documentation"
.PP 
.SS "static void Genetic_Algorithm\&.Utils\&.SettingsAccessor\&.ResetToDefaults ()\fC [static]\fP"

.PP
Retrieve \fBGA\fP parameters from a backup settings file 
.SS "static void Genetic_Algorithm\&.Utils\&.SettingsAccessor\&.SaveSettings ()\fC [static]\fP"

.PP
Write current settings state to permanent settings file 
.SH "Property Documentation"
.PP 
.SS "double Genetic_Algorithm\&.Utils\&.SettingsAccessor\&.CrossoverProbability\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Chance that two individuals will generate a meiotic offspring instead of continuing unchanged 
.SS "bool Genetic_Algorithm\&.Utils\&.SettingsAccessor\&.Elitism\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Indicates whether top individual of population should always be guaranteed to continue without changes 
.SS "double Genetic_Algorithm\&.Utils\&.SettingsAccessor\&.MutationProbability\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Chance that a single gene will mutate 
.SS "int Genetic_Algorithm\&.Utils\&.SettingsAccessor\&.PopulationSize\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Number of individuals per generation 
.SS "\fBSelectionType\fP Genetic_Algorithm\&.Utils\&.SettingsAccessor\&.Selection\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
\fBSelectionType\fP currently used 
.SS "double Genetic_Algorithm\&.Utils\&.SettingsAccessor\&.SteadyStateSurvivalRate\fC [static]\fP, \fC [get]\fP, \fC [set]\fP"

.PP
Percentage of individuals to automatically survive each generation 

.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
