.TH "Genetic_Algorithm" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBGA\fP"
.br
.ti -1c
.RI "namespace \fBProperties\fP"
.br
.ti -1c
.RI "namespace \fBUtils\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUniqueRandom\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
