.TH "Genetic_Algorithm.Utils" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Genetic_Algorithm.Utils
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSettingsAccessor\fP"
.br
.RI "Serves as an intermediary to the Genetic Algorithm's GaSettings\&.Default "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSelectionType\fP { \fBSelectionType\&.Roulette\fP, \fBSelectionType\&.SteadyState\fP }
.RI "Defines different methods of selecting individuals to advance into further generations ""
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBGenetic_Algorithm\&.Utils\&.SelectionType\fP\fC [strong]\fP"

.PP
Defines different methods of selecting individuals to advance into further generations 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRoulette \fP\fP
Every individual's fitness proportionally increases its chance to be selected\&. If an individua's fitness makes up 30% of the whole population's summed scores, the individual has 30% chance to be selected\&. 
.TP
\fB\fISteadyState \fP\fP
Larger group of individuals is selected to survive into next generation\&. Certain percentage of individuals gets 'killed', the remainder continues (and possibly gets mutated) and creates new offspring to fill the gap after the killed individuals\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
