.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/Forms/CustomControls/LabeledPolygonImage.cs" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/Forms/CustomControls/LabeledPolygonImage.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPolygons\&.Forms\&.CustomControls\&.LabeledPolygonImage\fP"
.br
.RI "Control containing a picture of a polygon, an optional description tag and a selection checkbox which appears when mouse-hovered over "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPolygons\&.Forms\&.CustomControls\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
