.TH "md__c_1___code_projects__genetic__algorithm_-__polygons__r_e_a_d_m_e" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1___code_projects__genetic__algorithm_-__polygons__r_e_a_d_m_ePolyGenetic Algorithm 
 \- \fIImplementation of a genetic algorithm, generic support for various domains, currently support for polygons (using their axial symmetry as a fitness function)\&.\fP
.PP
.SS "How to launch:"
.PP
After downloading the files, you can launch the app without any other necessary steps via the \fBPolyGaLauncher\fP in \fC\fBPolyGaLauncher\fP\\bin\\Release\\PolyGaLauncher\&.exe\fP
.PP
.SS "Main program components:"
.PP
.IP "\(bu" 2
Genetic Algorithm
.IP "  \(bu" 4
Adjust genetic algorithm parameters, choose between different fitness function calculators, run genetic algorithm
.PP

.IP "\(bu" 2
Population Manager
.IP "  \(bu" 4
Manage multiple polygons at once (automatic generation, saving, loading)
.PP

.IP "\(bu" 2
Shape Creator
.IP "  \(bu" 4
Define polygon shapes, colors, names
.PP

.PP
.PP
.SS "To create a new domain, the following needs to be done:"
.PP
.IP "\(bu" 2
[ ] Reference the '*Genetic_Algorithm*' library (\fC\fBGenetic_Algorithm\&.GA\&.Generics\fP\fP) 
.SS "Implement:"

.PP
.PP
.IP "\(bu" 2
[ ] \fBIGene(s)\fP
.IP "\(bu" 2
[ ] \fBIIndividual(s)\fP using your implemented IGene
.IP "\(bu" 2
[ ] \fBGeneticAlgortihm Adapter\fP (\fBCrossover\fP method between your IIndividuals, all other methods are already implemented generically)
.IP "\(bu" 2
[ ] \fBFitness Calculator(s)\fP evaluating your IIndividual's fitness
.IP "\(bu" 2
[ ] *(Optional: some sort of \fBfeedback\fP on the progress of your domain's GAs)* 
.PP

