.TH "Polygons.GA.FitnessCalculators.SymmetryIntersectionPenaltyFitnessCalculator" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.GA.FitnessCalculators.SymmetryIntersectionPenaltyFitnessCalculator \- 
.PP
\fBSee also:\fP
.RS 4
\fBBasicSymmetryFitnessCalculator\fP
.PP
.RE
.PP
Additonally reduces fitness for every intersecting edge pair in the polygon  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPolygons\&.GA\&.FitnessCalculators\&.BasicSymmetryFitnessCalculator\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override double \fBIndividualFitness\fP (\fBPolygonIndividual\fP individual)"
.br
.ti -1c
.RI "override string \fBToString\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "override string \fBName\fP\fC [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBSee also:\fP
.RS 4
\fBBasicSymmetryFitnessCalculator\fP
.PP
.RE
.PP
Additonally reduces fitness for every intersecting edge pair in the polygon 


.SH "Member Function Documentation"
.PP 
.SS "override double Polygons\&.GA\&.FitnessCalculators\&.SymmetryIntersectionPenaltyFitnessCalculator\&.IndividualFitness (\fBPolygonIndividual\fP individual)\fC [virtual]\fP"

.PP
Reimplemented from \fBPolygons\&.GA\&.FitnessCalculators\&.BasicSymmetryFitnessCalculator\fP\&.
.SS "override string Polygons\&.GA\&.FitnessCalculators\&.SymmetryIntersectionPenaltyFitnessCalculator\&.ToString ()"

.SH "Property Documentation"
.PP 
.SS "override string Polygons\&.GA\&.FitnessCalculators\&.SymmetryIntersectionPenaltyFitnessCalculator\&.Name\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
