.TH "Polygons.Forms.CrossroadForm" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.Forms.CrossroadForm \- Serves as a central form for the genetic algorithm - grants access to every important component of the application\&. Only one instance of this form can be run at once\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static \fBCrossroadForm\fP \fBInstance\fP\fC [get]\fP"
.br
.RI "Access an instance of \fBCrossroadForm\fP "
.in -1c
.SH "Detailed Description"
.PP 
Serves as a central form for the genetic algorithm - grants access to every important component of the application\&. Only one instance of this form can be run at once\&. 


.SH "Member Function Documentation"
.PP 
.SS "override void Polygons\&.Forms\&.CrossroadForm\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "\fBCrossroadForm\fP Polygons\&.Forms\&.CrossroadForm\&.Instance\fC [static]\fP, \fC [get]\fP"

.PP
Access an instance of \fBCrossroadForm\fP 

.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
