.TH "Polygons.Forms.DialogForms" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.Forms.DialogForms
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBChooseVerticesCountToImportDialog\fP"
.br
.RI "Helper dialog form used to select a single group of individuals with a uniform vertex count "
.ti -1c
.RI "class \fBDeleteFileConfirmation\fP"
.br
.ti -1c
.RI "struct \fBIndividualsOfVertexCountPair\fP"
.br
.RI "Structure used to transfer constructor data to ChooseVerticesCountToImportDialog\&. "
.ti -1c
.RI "class \fBShapeNameChooserPrompt\fP"
.br
.RI "Dialog box asking the user to specify a name for a polygon "
.ti -1c
.RI "class \fBShapeOverwritePromptForm\fP"
.br
.RI "Dialog box asking the user to confirm overwriting an existing file "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
