.TH "Polygons.Polygon" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.Polygon \- Represents a shape with a variable number of vertices, specific color and an optional name  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPolygons\&.IPolygon\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBShiftCenter\fP (Point newCenter)"
.br
.RI "Moves vertices of the polygon so that the specified point becomes the new center\&. "
.ti -1c
.RI "List< Point > \fBShiftedToCenter\fP (Point hypotheticalCenter)"
.br
.RI "Representation of this polygon's vertices adjusted to a hypothetical center "
.ti -1c
.RI "void \fBShiftCentroid\fP (Point newCentroid)"
.br
.RI "Moves all of polygon's vertices so that they match a new centroid position "
.ti -1c
.RI "List< Point > \fBShiftedToCentroid\fP (Point hypotheticalCentroid)"
.br
.RI "Representation of this polygon's vertices adjusted to a hypothetical centroid "
.ti -1c
.RI "void \fBShiftUpperLeftCorner\fP (Point shiftTo)"
.br
.RI "Change the coordinates of every vertex withotu distoring their relative positions\&. Left-most point of the polygon will share its X coordinate with the imaginary upper-left corner\&. Top-most point of the polygon will share its Y coordinate with the imaginary upper-left corner\&. "
.ti -1c
.RI "void \fBShiftVertices\fP (int dX, int dY)"
.br
.RI "Change the coordinates of every vertex without distorting their relative positions\&. "
.ti -1c
.RI "double \fBGetScalingFactor\fP (int normalizeToX, int normalizeToY)"
.br
.RI "Determine a proper resize value to fit polygon into a container of specified size "
.ti -1c
.RI "\fBPolygon\fP (List< Point > vertices, Color outlineColor=default(Color), string name=default(string))"
.br
.RI "Construct polygon from a list of vertices, optionally specify its color and name "
.ti -1c
.RI "\fBPolygon\fP (\fBPolygon\fP original, double resizeFactor)"
.br
.RI "Construct polygon according to a template, adjust relative positions of vertices by a scaling factor "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static List< Point > \fBShiftedVertices\fP (List< Point > vertices, int dX, int dY)"
.br
.RI "Moves vertices to a new location (specified by amount of movement on X and Y axes\&. "
.ti -1c
.RI "static List< Point > \fBShiftedVertices\fP (List< Point > vertices, Point shiftToCorner)"
.br
.RI "Moves vertices to a new location (specified by upper left corner of the whole shape)\&. "
.ti -1c
.RI "static \fBPolygon\fP \fBCopy\fP (\fBPolygon\fP original)"
.br
.RI "Create an identical copy of polygon "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Color \fBOutlineColor\fP\fC [get, set]\fP"
.br
.RI "Color of the connecting lines and points of the polygon "
.ti -1c
.RI "string \fBName\fP\fC [get, set]\fP"
.br
.RI "Name assigned to the polygon "
.ti -1c
.RI "List< Point > \fBVertices\fP\fC [get]\fP"
.br
.RI "All of the polygon's vertices represented as Points "
.ti -1c
.RI "int \fBVerticesCount\fP\fC [get]\fP"
.br
.RI "Number of vertices "
.ti -1c
.RI "Point \fBCenter\fP\fC [get]\fP"
.br
.RI "Point which is the average of the polygon's left/right-most and top/lower-most vertices "
.ti -1c
.RI "Point \fBCentroid\fP\fC [get]\fP"
.br
.RI "Point which is the average of every vertex's coordinates "
.in -1c
.SH "Detailed Description"
.PP 
Represents a shape with a variable number of vertices, specific color and an optional name 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Polygons\&.Polygon\&.Polygon (List< Point > vertices, Color outlineColor = \fCdefault(Color)\fP, string name = \fCdefault(string)\fP)"

.PP
Construct polygon from a list of vertices, optionally specify its color and name 
.PP
\fBParameters:\fP
.RS 4
\fIvertices\fP 
.br
\fIoutlineColor\fP 
.br
\fIname\fP 
.RE
.PP

.SS "Polygons\&.Polygon\&.Polygon (\fBPolygon\fP original, double resizeFactor)"

.PP
Construct polygon according to a template, adjust relative positions of vertices by a scaling factor 
.PP
\fBParameters:\fP
.RS 4
\fIoriginal\fP Template polygon
.br
\fIresizeFactor\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "static \fBPolygon\fP Polygons\&.Polygon\&.Copy (\fBPolygon\fP original)\fC [static]\fP"

.PP
Create an identical copy of polygon 
.PP
\fBParameters:\fP
.RS 4
\fIoriginal\fP Template polygon
.RE
.PP
\fBReturns:\fP
.RS 4
Identical copy of original
.RE
.PP

.SS "double Polygons\&.Polygon\&.GetScalingFactor (int normalizeToX, int normalizeToY)"

.PP
Determine a proper resize value to fit polygon into a container of specified size 
.PP
\fBParameters:\fP
.RS 4
\fInormalizeToX\fP Horizontal size of container
.br
\fInormalizeToY\fP Vertical size of container
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP

.SS "void Polygons\&.Polygon\&.ShiftCenter (Point newCenter)"

.PP
Moves vertices of the polygon so that the specified point becomes the new center\&. 
.PP
\fBParameters:\fP
.RS 4
\fInewCenter\fP Location to become the new center after the shift
.RE
.PP

.SS "void Polygons\&.Polygon\&.ShiftCentroid (Point newCentroid)"

.PP
Moves all of polygon's vertices so that they match a new centroid position 
.PP
\fBParameters:\fP
.RS 4
\fInewCentroid\fP 
.RE
.PP

.SS "List<Point> Polygons\&.Polygon\&.ShiftedToCenter (Point hypotheticalCenter)"

.PP
Representation of this polygon's vertices adjusted to a hypothetical center 
.PP
\fBParameters:\fP
.RS 4
\fIhypotheticalCenter\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
List of polygon's vertices adjusted to center
.RE
.PP

.SS "List<Point> Polygons\&.Polygon\&.ShiftedToCentroid (Point hypotheticalCentroid)"

.PP
Representation of this polygon's vertices adjusted to a hypothetical centroid 
.PP
\fBParameters:\fP
.RS 4
\fIhypotheticalCentroid\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
List of polygon's vertices adjusted to centroid
.RE
.PP

.SS "static List<Point> Polygons\&.Polygon\&.ShiftedVertices (List< Point > vertices, int dX, int dY)\fC [static]\fP"

.PP
Moves vertices to a new location (specified by amount of movement on X and Y axes\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvertices\fP Vertices to be shifted
.br
\fIdX\fP Amount of movement on X axis
.br
\fIdY\fP Amount of movement on Y axis
.RE
.PP
\fBReturns:\fP
.RS 4
Vertices adjusted to a new location
.RE
.PP

.SS "static List<Point> Polygons\&.Polygon\&.ShiftedVertices (List< Point > vertices, Point shiftToCorner)\fC [static]\fP"

.PP
Moves vertices to a new location (specified by upper left corner of the whole shape)\&. 
.PP
\fBParameters:\fP
.RS 4
\fIvertices\fP Vertices to be shifted
.br
\fIshiftToCorner\fP Upper left corner of the desired output
.RE
.PP
\fBReturns:\fP
.RS 4
Vertices adjusted to a new location
.RE
.PP

.SS "void Polygons\&.Polygon\&.ShiftUpperLeftCorner (Point shiftTo)"

.PP
Change the coordinates of every vertex withotu distoring their relative positions\&. Left-most point of the polygon will share its X coordinate with the imaginary upper-left corner\&. Top-most point of the polygon will share its Y coordinate with the imaginary upper-left corner\&. 
.PP
\fBParameters:\fP
.RS 4
\fIshiftTo\fP Imaginary upper-left corner to shift to
.RE
.PP

.SS "void Polygons\&.Polygon\&.ShiftVertices (int dX, int dY)"

.PP
Change the coordinates of every vertex without distorting their relative positions\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdX\fP Shift on the horizontal axis
.br
\fIdY\fP Shift on the vertical axis
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "Point Polygons\&.Polygon\&.Center\fC [get]\fP"

.PP
Point which is the average of the polygon's left/right-most and top/lower-most vertices 
.SS "Point Polygons\&.Polygon\&.Centroid\fC [get]\fP"

.PP
Point which is the average of every vertex's coordinates 
.SS "string Polygons\&.Polygon\&.Name\fC [get]\fP, \fC [set]\fP"

.PP
Name assigned to the polygon 
.SS "Color Polygons\&.Polygon\&.OutlineColor\fC [get]\fP, \fC [set]\fP"

.PP
Color of the connecting lines and points of the polygon 
.SS "List<Point> Polygons\&.Polygon\&.Vertices\fC [get]\fP"

.PP
All of the polygon's vertices represented as Points 
.SS "int Polygons\&.Polygon\&.VerticesCount\fC [get]\fP"

.PP
Number of vertices 

.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
