.TH "Polygons.IPolygon" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.IPolygon \- Represents a shape with a variable number of vertices, specific color and an optional name  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBPolygons\&.Polygon\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBVerticesCount\fP\fC [get]\fP"
.br
.RI "Number of vertices "
.ti -1c
.RI "Color \fBOutlineColor\fP\fC [get, set]\fP"
.br
.RI "Color of the lines connecting vertices "
.ti -1c
.RI "List< Point > \fBVertices\fP\fC [get]\fP"
.br
.RI "List representation of the polygon's vertices "
.ti -1c
.RI "Point \fBCenter\fP\fC [get]\fP"
.br
.RI "Point which is the average of the polygon's left/right-most and top/lower-most vertices "
.ti -1c
.RI "Point \fBCentroid\fP\fC [get]\fP"
.br
.RI "Point which is the average of every vertex's coordinates "
.in -1c
.SH "Detailed Description"
.PP 
Represents a shape with a variable number of vertices, specific color and an optional name 


.SH "Property Documentation"
.PP 
.SS "Point Polygons\&.IPolygon\&.Center\fC [get]\fP"

.PP
Point which is the average of the polygon's left/right-most and top/lower-most vertices 
.SS "Point Polygons\&.IPolygon\&.Centroid\fC [get]\fP"

.PP
Point which is the average of every vertex's coordinates 
.SS "Color Polygons\&.IPolygon\&.OutlineColor\fC [get]\fP, \fC [set]\fP"

.PP
Color of the lines connecting vertices 
.SS "List<Point> Polygons\&.IPolygon\&.Vertices\fC [get]\fP"

.PP
List representation of the polygon's vertices 
.SS "int Polygons\&.IPolygon\&.VerticesCount\fC [get]\fP"

.PP
Number of vertices 

.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
