.TH "Polygons.GA.IPolygonGene" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.GA.IPolygonGene \- Gene which can be included in a \fBPolygonIndividual\fP's genome  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGenetic_Algorithm\&.GA\&.Generics\&.IGene< System\&.Drawing\&.Point >\fP\&.
.PP
Inherited by \fBPolygons\&.GA\&.SimplePolygonGene\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateAngularRepresentation\fP (System\&.Drawing\&.Point centroid)"
.br
.RI "Rebuild DistanceFromCentroid and AngleRelativeToCentroid properties based on a new centroid point and current X,Y coordinates "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBX\fP\fC [get]\fP"
.br
.RI "X coordinate of the gene's encoded point "
.ti -1c
.RI "int \fBY\fP\fC [get]\fP"
.br
.RI "Y coordinate of the gene's encoded point "
.ti -1c
.RI "double \fBDistanceFromCentroid\fP\fC [get]\fP"
.br
.RI "Distance between the point encoded by the gene and the whole individual's (polygon's) centroid "
.ti -1c
.RI "Angle \fBAngleRelativeToCentroid\fP\fC [get]\fP"
.br
.RI "Represents angle on a circle relative to whole individual's centroid\&. 0° to the right, 90° up, 180° left, 270° down "
.in -1c
.SH "Detailed Description"
.PP 
Gene which can be included in a \fBPolygonIndividual\fP's genome 


.SH "Member Function Documentation"
.PP 
.SS "void Polygons\&.GA\&.IPolygonGene\&.UpdateAngularRepresentation (System\&.Drawing\&.Point centroid)"

.PP
Rebuild DistanceFromCentroid and AngleRelativeToCentroid properties based on a new centroid point and current X,Y coordinates 
.PP
\fBParameters:\fP
.RS 4
\fIcentroid\fP New centroid to update according to
.RE
.PP

.SH "Property Documentation"
.PP 
.SS "Angle Polygons\&.GA\&.IPolygonGene\&.AngleRelativeToCentroid\fC [get]\fP"

.PP
Represents angle on a circle relative to whole individual's centroid\&. 0° to the right, 90° up, 180° left, 270° down 
.SS "double Polygons\&.GA\&.IPolygonGene\&.DistanceFromCentroid\fC [get]\fP"

.PP
Distance between the point encoded by the gene and the whole individual's (polygon's) centroid 
.SS "int Polygons\&.GA\&.IPolygonGene\&.X\fC [get]\fP"

.PP
X coordinate of the gene's encoded point 
.SS "int Polygons\&.GA\&.IPolygonGene\&.Y\fC [get]\fP"

.PP
Y coordinate of the gene's encoded point 

.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
