.TH "Polygons.GA.PolygonAdapter" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.GA.PolygonAdapter \- \fBGeneticAlgorithmAdapter<PolygonIndividual, IPolygonGene>\fP which contains the logic for crossover of the \fBPolygonIndividual\fPs  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGenetic_Algorithm\&.GA\&.Generics\&.GeneticAlgorithmAdapter< PolygonIndividual, IPolygonGene >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolygonAdapter\fP (\fBIFitnessCalculator\fP< \fBPolygonIndividual\fP, \fBIPolygonGene\fP > \fBfitnessCalculator\fP)"
.br
.ti -1c
.RI "override \fBPolygonIndividual\fP \fBCrossOver\fP (\fBPolygonIndividual\fP parent1, \fBPolygonIndividual\fP parent2)"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBGeneticAlgorithmAdapter<PolygonIndividual, IPolygonGene>\fP which contains the logic for crossover of the \fBPolygonIndividual\fPs 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Polygons\&.GA\&.PolygonAdapter\&.PolygonAdapter (\fBIFitnessCalculator\fP< \fBPolygonIndividual\fP, \fBIPolygonGene\fP > fitnessCalculator)"

.SH "Member Function Documentation"
.PP 
.SS "override \fBPolygonIndividual\fP Polygons\&.GA\&.PolygonAdapter\&.CrossOver (\fBPolygonIndividual\fP parent1, \fBPolygonIndividual\fP parent2)"


.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
