.TH "Polygons.Forms.CustomControls" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.Forms.CustomControls
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGaComponentIcon\fP"
.br
.ti -1c
.RI "class \fBLabeledPolygonImage\fP"
.br
.RI "Control containing a picture of a polygon, an optional description tag and a selection checkbox which appears when mouse-hovered over "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
