.TH "Polygons.Forms" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.Forms
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBCustomControls\fP"
.br
.ti -1c
.RI "namespace \fBDialogForms\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCrossroadForm\fP"
.br
.RI "Serves as a central form for the genetic algorithm - grants access to every important component of the application\&. Only one instance of this form can be run at once\&. "
.ti -1c
.RI "class \fBGaViewerForm\fP"
.br
.RI "Visualization and customization of a Genetic algorithm with \fBPolygons\fP\&. "
.ti -1c
.RI "class \fBPolygonCreationForm\fP"
.br
.RI "Form allowing user to specify and modify a custom shape "
.ti -1c
.RI "class \fBPopulationGeneratorForm\fP"
.br
.RI "Management of multiple Genetic algorithm polygon individuals "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
