.TH "Polygons.GA.FitnessCalculators" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.GA.FitnessCalculators
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBasicSymmetryFitnessCalculator\fP"
.br
.RI "For every \fBIPolygonGene\fP, finds its closest Y axis mirrored relative and decreases fitness based on the distance difference from an ideal relative's position "
.ti -1c
.RI "class \fBCalculatorRetriever\fP"
.br
.RI "Provides a centralised access to fitness calculators intended for \fBPolygonIndividual\fPs "
.ti -1c
.RI "class \fBSymmetryIntersectionPenaltyFitnessCalculator\fP"
.br
.RI "
.PP
\fBSee also:\fP
.RS 4
\fBBasicSymmetryFitnessCalculator\fP
.PP
.RE
.PP
Additonally reduces fitness for every intersecting edge pair in the polygon "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
