.TH "Polygons.GA.SimplePolygonGene" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.GA.SimplePolygonGene \- Represents genetic information about one vertex of a polygon  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBPolygons\&.GA\&.IPolygonGene\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUpdateAngularRepresentation\fP (Point centroid)"
.br
.ti -1c
.RI "void \fBUpdatePointRepresentation\fP ()"
.br
.ti -1c
.RI "\fBSimplePolygonGene\fP (Point vertexPosition, Point centroid)"
.br
.ti -1c
.RI "void \fBMutate\fP ()"
.br
.ti -1c
.RI "Point \fBDecode\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBX\fP\fC [get]\fP"
.br
.ti -1c
.RI "int \fBY\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBDistanceFromCentroid\fP\fC [get]\fP"
.br
.ti -1c
.RI "Angle \fBAngleRelativeToCentroid\fP\fC [get]\fP"
.br
.RI "Represents angle on a circle relative to whole individual's centroid\&. 0° to the right, 90° up, 180° left, 270° down "
.in -1c
.SH "Detailed Description"
.PP 
Represents genetic information about one vertex of a polygon 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Polygons\&.GA\&.SimplePolygonGene\&.SimplePolygonGene (Point vertexPosition, Point centroid)"

.SH "Member Function Documentation"
.PP 
.SS "Point Polygons\&.GA\&.SimplePolygonGene\&.Decode ()"

.SS "void Polygons\&.GA\&.SimplePolygonGene\&.Mutate ()"

.SS "void Polygons\&.GA\&.SimplePolygonGene\&.UpdateAngularRepresentation (Point centroid)"

.SS "void Polygons\&.GA\&.SimplePolygonGene\&.UpdatePointRepresentation ()"

.SH "Property Documentation"
.PP 
.SS "Angle Polygons\&.GA\&.SimplePolygonGene\&.AngleRelativeToCentroid\fC [get]\fP"

.PP
Represents angle on a circle relative to whole individual's centroid\&. 0° to the right, 90° up, 180° left, 270° down 
.SS "double Polygons\&.GA\&.SimplePolygonGene\&.DistanceFromCentroid\fC [get]\fP"

.SS "int Polygons\&.GA\&.SimplePolygonGene\&.X\fC [get]\fP"

.SS "int Polygons\&.GA\&.SimplePolygonGene\&.Y\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
