.TH "Polygons.Forms.GaViewerForm" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.Forms.GaViewerForm \- Visualization and customization of a Genetic algorithm with \fBPolygons\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGaViewerForm\fP (IEnumerable< \fBIFitnessCalculator\fP< \fBPolygonIndividual\fP, \fBIPolygonGene\fP >> availableFitnessCalculators)"
.br
.RI "Creates an instance of a form for visualizing and customizing the run of a Genetic algorithm for \fBPolygons\fP "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnGaGenerationComplete\fP (\fBGaEventArgs\fP< \fBPolygonIndividual\fP, \fBIPolygonGene\fP > e)"
.br
.RI "Process the event of a generation being finished from the underlying GeneticAlgorithm<PolygonIndividual, IPolygonGene> "
.ti -1c
.RI "virtual void \fBOnGaInitialised\fP (\fBGaEventArgs\fP< \fBPolygonIndividual\fP, \fBIPolygonGene\fP > e)"
.br
.RI "Process the event of the underlying GaEventArgs<PolygonIndividual, IPolygonGene> having been initialised "
.ti -1c
.RI "override bool \fBProcessDialogKey\fP (Keys keyData)"
.br
.RI "Safely close form on ESC press "
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Visualization and customization of a Genetic algorithm with \fBPolygons\fP\&. 

Provides following features (among others): 
.PD 0

.IP "\(bu" 2
Import previously created individuals into a \fBGA\fP's initial population 
.IP "\(bu" 2
Modify parameters of the genetic algorithm 
.IP "\(bu" 2
Change frequency of generations in the \fBGA\fP to be viewed 
.IP "\(bu" 2
Change frequency of generations to be saved during the run of the \fBGA\fP 
.IP "\(bu" 2
View generated populations and change basic properties of the images 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Polygons\&.Forms\&.GaViewerForm\&.GaViewerForm (IEnumerable< \fBIFitnessCalculator\fP< \fBPolygonIndividual\fP, \fBIPolygonGene\fP >> availableFitnessCalculators)"

.PP
Creates an instance of a form for visualizing and customizing the run of a Genetic algorithm for \fBPolygons\fP 
.PP
\fBParameters:\fP
.RS 4
\fIavailableFitnessCalculators\fP All Fitness calculators which the form can load into its options
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "override void Polygons\&.Forms\&.GaViewerForm\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SS "virtual void Polygons\&.Forms\&.GaViewerForm\&.OnGaGenerationComplete (\fBGaEventArgs\fP< \fBPolygonIndividual\fP, \fBIPolygonGene\fP > e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Process the event of a generation being finished from the underlying GeneticAlgorithm<PolygonIndividual, IPolygonGene> 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP GaEventArgs<PolygonIndividual, IPolygonGene> holding information about the finished generation
.RE
.PP

.SS "virtual void Polygons\&.Forms\&.GaViewerForm\&.OnGaInitialised (\fBGaEventArgs\fP< \fBPolygonIndividual\fP, \fBIPolygonGene\fP > e)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Process the event of the underlying GaEventArgs<PolygonIndividual, IPolygonGene> having been initialised 
.PP
\fBParameters:\fP
.RS 4
\fIe\fP GaEventArgs<PolygonIndividual, IPolygonGene> holding information about the initial generation
.RE
.PP

.SS "override bool Polygons\&.Forms\&.GaViewerForm\&.ProcessDialogKey (Keys keyData)\fC [protected]\fP"

.PP
Safely close form on ESC press 
.PP
\fBParameters:\fP
.RS 4
\fIkeyData\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
True to close form, False otherwise
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
