.TH "Polygons.PolygonGenerator" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.PolygonGenerator \- Provides static methods for generation of polygons  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBPolygon\fP \fBRandomPolygon\fP ()"
.br
.RI "Generate a random polygon with a random number of vertices "
.ti -1c
.RI "static \fBPolygon\fP \fBRandomPolygon\fP (int verticesCount)"
.br
.RI "Generate a random polygon with the specified number of vertices "
.in -1c
.SH "Detailed Description"
.PP 
Provides static methods for generation of polygons 


.SH "Member Function Documentation"
.PP 
.SS "static \fBPolygon\fP Polygons\&.PolygonGenerator\&.RandomPolygon ()\fC [static]\fP"

.PP
Generate a random polygon with a random number of vertices 
.PP
\fBReturns:\fP
.RS 4
Random polygon
.RE
.PP

.SS "static \fBPolygon\fP Polygons\&.PolygonGenerator\&.RandomPolygon (int verticesCount)\fC [static]\fP"

.PP
Generate a random polygon with the specified number of vertices 
.PP
\fBParameters:\fP
.RS 4
\fIverticesCount\fP Number of vertices of the result polygon
.RE
.PP
\fBReturns:\fP
.RS 4
Random polygon with 'n' vertices
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
