.TH "Polygons.GA.PolygonIndividual" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.GA.PolygonIndividual \- \fBIIndividual<IPolygonGene>\fP which introduces the structure of \fBIPolygon\fP into a genetic algorithm  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBGenetic_Algorithm\&.GA\&.Generics\&.IIndividual< IPolygonGene >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPolygonIndividual\fP ()"
.br
.ti -1c
.RI "\fBPolygonIndividual\fP (\fBPolygon\fP p)"
.br
.ti -1c
.RI "\fBPolygonIndividual\fP (IEnumerable< \fBIPolygonGene\fP > genome, string name, Color color)"
.br
.ti -1c
.RI "void \fBInvalidateFitness\fP ()"
.br
.ti -1c
.RI "void \fBMutate\fP (double mutationProbability)"
.br
.ti -1c
.RI "bool \fBEquals\fP (\fBIIndividual\fP< \fBIPolygonGene\fP > other)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBPolygon\fP \fBPolygon\fP\fC [get]\fP"
.br
.ti -1c
.RI "ICollection< \fBIPolygonGene\fP > \fBGenome\fP\fC [get]\fP"
.br
.ti -1c
.RI "static double \fBInvalidFitnessIndicator\fP\fC [get]\fP"
.br
.ti -1c
.RI "double \fBFitness\fP\fC [get, set]\fP"
.br
.ti -1c
.RI "string \fBName\fP\fC [get]\fP"
.br
.ti -1c
.RI "bool \fBIsElite\fP\fC [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBIIndividual<IPolygonGene>\fP which introduces the structure of \fBIPolygon\fP into a genetic algorithm 


.SH "Constructor & Destructor Documentation"
.PP 
.SS "Polygons\&.GA\&.PolygonIndividual\&.PolygonIndividual ()"

.SS "Polygons\&.GA\&.PolygonIndividual\&.PolygonIndividual (\fBPolygon\fP p)"

.SS "Polygons\&.GA\&.PolygonIndividual\&.PolygonIndividual (IEnumerable< \fBIPolygonGene\fP > genome, string name, Color color)"

.SH "Member Function Documentation"
.PP 
.SS "bool Polygons\&.GA\&.PolygonIndividual\&.Equals (\fBIIndividual\fP< \fBIPolygonGene\fP > other)"

.SS "void Polygons\&.GA\&.PolygonIndividual\&.InvalidateFitness ()"

.SS "void Polygons\&.GA\&.PolygonIndividual\&.Mutate (double mutationProbability)"

.SH "Property Documentation"
.PP 
.SS "double Polygons\&.GA\&.PolygonIndividual\&.Fitness\fC [get]\fP, \fC [set]\fP"

.SS "ICollection<\fBIPolygonGene\fP> Polygons\&.GA\&.PolygonIndividual\&.Genome\fC [get]\fP"

.SS "double Polygons\&.GA\&.PolygonIndividual\&.InvalidFitnessIndicator\fC [static]\fP, \fC [get]\fP"

.SS "bool Polygons\&.GA\&.PolygonIndividual\&.IsElite\fC [get]\fP, \fC [set]\fP"

.SS "string Polygons\&.GA\&.PolygonIndividual\&.Name\fC [get]\fP"

.SS "\fBPolygon\fP Polygons\&.GA\&.PolygonIndividual\&.Polygon\fC [get]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
