.TH "Polygons.GA.FitnessCalculators.CalculatorRetriever" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.GA.FitnessCalculators.CalculatorRetriever \- Provides a centralised access to fitness calculators intended for \fBPolygonIndividual\fPs  

.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static IEnumerable< \fBIFitnessCalculator\fP< \fBPolygonIndividual\fP, \fBIPolygonGene\fP > > \fBGetAllCalculators\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Provides a centralised access to fitness calculators intended for \fBPolygonIndividual\fPs 


.SH "Member Function Documentation"
.PP 
.SS "static IEnumerable<\fBIFitnessCalculator\fP<\fBPolygonIndividual\fP, \fBIPolygonGene\fP> > Polygons\&.GA\&.FitnessCalculators\&.CalculatorRetriever\&.GetAllCalculators ()\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
