.TH "Polygons.GA" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.GA
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBFitnessCalculators\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIPolygonGene\fP"
.br
.RI "Gene which can be included in a \fBPolygonIndividual\fP's genome "
.ti -1c
.RI "class \fBPolygonAdapter\fP"
.br
.RI "\fBGeneticAlgorithmAdapter<PolygonIndividual, IPolygonGene>\fP which contains the logic for crossover of the \fBPolygonIndividual\fPs "
.ti -1c
.RI "class \fBPolygonIndividual\fP"
.br
.RI "\fBIIndividual<IPolygonGene>\fP which introduces the structure of \fBIPolygon\fP into a genetic algorithm "
.ti -1c
.RI "class \fBSimplePolygonGene\fP"
.br
.RI "Represents genetic information about one vertex of a polygon "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
