.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/Polygon/Polygon.cs" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/Polygon/Polygon.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPolygons\&.Polygon\fP"
.br
.RI "Represents a shape with a variable number of vertices, specific color and an optional name "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPolygons\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
