.TH "C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/Polygon/PolygonXmlHandler.cs" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/_CodeProjects/Genetic Algorithm - Polygons/Polygons/Polygons/Polygon/PolygonXmlHandler.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPolygons\&.PolygonXmlHandler\fP"
.br
.RI "Provides static methods for loading and saving \fBPolygons\fP from/to \&.xml files "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBPolygons\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
