.TH "Polygons.Forms.PopulationGeneratorForm" 3 "Sat Sep 16 2017" "Version 1.1.2" "PolyGenetic Algorithm" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Polygons.Forms.PopulationGeneratorForm \- Management of multiple Genetic algorithm polygon individuals  

.SH SYNOPSIS
.br
.PP
.PP
Inherits Form\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPopulationGeneratorForm\fP ()"
.br
.RI "Creates a population management form for Genetic algorithm "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override bool \fBProcessDialogKey\fP (Keys keyData)"
.br
.RI "Safely close form on ESC press "
.ti -1c
.RI "override void \fBDispose\fP (bool disposing)"
.br
.RI "Clean up any resources being used\&. "
.in -1c
.SH "Detailed Description"
.PP 
Management of multiple Genetic algorithm polygon individuals 

Provides following features (among others): 
.PD 0

.IP "\(bu" 2
Import previously created shapes 
.IP "\(bu" 2
Manage saved shapes in larger quantities 
.IP "\(bu" 2
Sort viewed images by their fitness 
.IP "\(bu" 2
Change basic properties of the images 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "Polygons\&.Forms\&.PopulationGeneratorForm\&.PopulationGeneratorForm ()"

.PP
Creates a population management form for Genetic algorithm 
.SH "Member Function Documentation"
.PP 
.SS "override void Polygons\&.Forms\&.PopulationGeneratorForm\&.Dispose (bool disposing)\fC [protected]\fP"

.PP
Clean up any resources being used\&. 
.PP
\fBParameters:\fP
.RS 4
\fIdisposing\fP true if managed resources should be disposed; otherwise, false\&.
.RE
.PP

.SS "override bool Polygons\&.Forms\&.PopulationGeneratorForm\&.ProcessDialogKey (Keys keyData)\fC [protected]\fP"

.PP
Safely close form on ESC press 
.PP
\fBParameters:\fP
.RS 4
\fIkeyData\fP 
.RE
.PP
\fBReturns:\fP
.RS 4
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PolyGenetic Algorithm from the source code\&.
