//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Genetic_Algorithm.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class GaSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static GaSettings defaultInstance = ((GaSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new GaSettings())));
        
        public static GaSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.9")]
        public double CrossoverProbability {
            get {
                return ((double)(this["CrossoverProbability"]));
            }
            set {
                this["CrossoverProbability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.05")]
        public double MutationProbability {
            get {
                return ((double)(this["MutationProbability"]));
            }
            set {
                this["MutationProbability"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double SteadyStateSurvivalRate {
            get {
                return ((double)(this["SteadyStateSurvivalRate"]));
            }
            set {
                this["SteadyStateSurvivalRate"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Elitism {
            get {
                return ((bool)(this["Elitism"]));
            }
            set {
                this["Elitism"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Roulette")]
        public string SelectionType {
            get {
                return ((string)(this["SelectionType"]));
            }
            set {
                this["SelectionType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int PopulationSize {
            get {
                return ((int)(this["PopulationSize"]));
            }
            set {
                this["PopulationSize"] = value;
            }
        }
    }
}
